### ISSUE TITLE
Adding a dependency makes git dependencies to reinstall

### ISSUE THREAD

**Issue by llelf** [sol/tinc#40]
This is easier to describe with a simple example:

```
git clone https://github.com/llelf/tinc-issue
cd tinc-issue
cat tinc.yaml

> dependencies:
>   - name: dependency
>     path: dependency/

git checkout 1901c
tinc

> Installing acme-dont-1.1
> Installing dependency-0.1.0.0

git checkout 34cb2
# that just adds acme-pointful-numbers dependency to tinc-issue.cabal
tinc

> Reusing split-0.2.3
> Reusing acme-dont-1.1
> Reusing dependency-0.1.0.0
> Installing acme-pointful-numbers-0.1.2.4
> …
> In order, the following will be installed:
> acme-pointful-numbers-0.1.2.4 (new package)
> dependency-0.1.0.0 (reinstall)
> 
```

(I haven't actually done any investigation.)

Wonder if there is there a way to avoid that?

**Comment by sol** [comment]
When I tried it I see the same behaviour.  Haven't looked into it deeper, but looks like a bug to me (possibly a limitation with `cabal`).

**Comment by sol** [comment]
@llelf I think this is actually a bug in `cabal-install`.  But we can work around it by not `add-source` reusable dependencies.

Thanks a lot for reporting this!
